name: dashboard_app_design
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Icons
  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.7.0
  
  # Utilities
  intl: ^0.19.0
  http: ^1.2.0
  permission_handler: ^11.3.1
  
  # Media & Notifications
  flutter_tts: ^4.1.0
  flutter_local_notifications: ^17.1.0
  
  # Mencegah aplikasi tidur saat kabel USB dicabut
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true